// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs_gen

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/posts": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    },
                    {
                        "CSRFToken": []
                    }
                ],
                "description": "Returns admin list for current actor scope (own drafts or all posts).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-posts"
                ],
                "summary": "List manageable posts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.PostResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.ErrorResponse"
                        }
                    },
                    "504": {
                        "description": "Gateway Timeout",
                        "schema": {
                            "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    },
                    {
                        "CSRFToken": []
                    }
                ],
                "description": "Create a new draft post under admin workflow.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-posts"
                ],
                "summary": "Create post draft",
                "parameters": [
                    {
                        "description": "create post payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.CreatePostRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.ErrorResponse"
                        }
                    },
                    "504": {
                        "description": "Gateway Timeout",
                        "schema": {
                            "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/posts": {
            "get": {
                "description": "Public read-only endpoint for published content.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "List published posts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.PostResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.ErrorResponse"
                        }
                    },
                    "504": {
                        "description": "Gateway Timeout",
                        "schema": {
                            "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/posts/{id}": {
            "get": {
                "description": "Public endpoint that returns one published post by numeric ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Get published post",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "post id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.PostResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.ErrorResponse"
                        }
                    },
                    "504": {
                        "description": "Gateway Timeout",
                        "schema": {
                            "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/system/check-db": {
            "post": {
                "description": "Validate DB connection using setup credentials.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "setup"
                ],
                "summary": "Check database connection",
                "parameters": [
                    {
                        "description": "database connection payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.CheckDBRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/system/setup": {
            "post": {
                "description": "Persist setup config and initialize system data.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "setup"
                ],
                "summary": "Install system",
                "parameters": [
                    {
                        "description": "setup payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.SystemSetupRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/system/status": {
            "get": {
                "description": "Returns installation status in setup mode.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "setup"
                ],
                "summary": "Setup status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.SystemStatusResponse"
                        }
                    }
                }
            }
        },
        "/users/login": {
            "post": {
                "description": "Authenticate and establish a cookie-based session.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "login payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.UserLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/logout": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    },
                    {
                        "CSRFToken": []
                    }
                ],
                "description": "Destroy the current session cookies.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Logout",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.MessageResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/register": {
            "post": {
                "description": "Create a normal user account.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register user",
                "parameters": [
                    {
                        "description": "register payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.UserRegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "KaldalisCMS_internal_api_v1_dto.AuthorResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "KaldalisCMS_internal_api_v1_dto.CategoryResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "KaldalisCMS_internal_api_v1_dto.CheckDBRequest": {
            "type": "object",
            "required": [
                "host",
                "name",
                "port",
                "user"
            ],
            "properties": {
                "host": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "pass": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "KaldalisCMS_internal_api_v1_dto.CreatePostRequest": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "category_id": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "cover": {
                    "type": "string",
                    "maxLength": 255
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "title": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                }
            }
        },
        "KaldalisCMS_internal_api_v1_dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "KaldalisCMS_internal_api_v1_dto.LoginResponse": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.LoginUserResponse"
                }
            }
        },
        "KaldalisCMS_internal_api_v1_dto.LoginUserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "role": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "KaldalisCMS_internal_api_v1_dto.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "KaldalisCMS_internal_api_v1_dto.PostResponse": {
            "type": "object",
            "properties": {
                "author": {
                    "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.AuthorResponse"
                },
                "category": {
                    "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.CategoryResponse"
                },
                "content": {
                    "type": "string"
                },
                "cover": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "slug": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/KaldalisCMS_internal_api_v1_dto.TagResponse"
                    }
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "KaldalisCMS_internal_api_v1_dto.SystemSetupRequest": {
            "type": "object",
            "required": [
                "admin_email",
                "admin_password",
                "admin_username",
                "site_name"
            ],
            "properties": {
                "admin_can_delete": {
                    "type": "boolean"
                },
                "admin_email": {
                    "type": "string",
                    "maxLength": 255
                },
                "admin_full_access": {
                    "type": "boolean"
                },
                "admin_password": {
                    "type": "string",
                    "maxLength": 72,
                    "minLength": 8
                },
                "admin_username": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                },
                "allow_anonymous_read": {
                    "description": "Permissions Config (Fine-grained)",
                    "type": "boolean"
                },
                "db_host": {
                    "description": "Database Config",
                    "type": "string"
                },
                "db_name": {
                    "type": "string"
                },
                "db_pass": {
                    "type": "string"
                },
                "db_port": {
                    "type": "integer"
                },
                "db_user": {
                    "type": "string"
                },
                "site_name": {
                    "description": "Site Config",
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "user_can_upload": {
                    "type": "boolean"
                }
            }
        },
        "KaldalisCMS_internal_api_v1_dto.SystemStatusResponse": {
            "type": "object",
            "properties": {
                "installed": {
                    "type": "boolean"
                },
                "site_name": {
                    "type": "string"
                }
            }
        },
        "KaldalisCMS_internal_api_v1_dto.TagResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "KaldalisCMS_internal_api_v1_dto.UserLoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "KaldalisCMS_internal_api_v1_dto.UserRegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "username": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                }
            }
        }
    },
    "securityDefinitions": {
        "CSRFToken": {
            "type": "apiKey",
            "name": "X-CSRF-Token",
            "in": "header"
        },
        "CookieAuth": {
            "type": "apiKey",
            "name": "kaldalis_auth",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "dev",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "KaldalisCMS API",
	Description:      "KaldalisCMS backend API documentation.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
